name:  Pipeline com testes unitários

on:

 # schedule:
 # - cron: '0 */6 * * 5'  # https://crontab.guru/ #
  
  push:               # EXECUÇÃO A CADA PUSH NA BRANCH MAIN
    
     
      
  workflow_dispatch:      # EXECUÇÃO MANUAL
  

jobs:
        
      
  deploy-dev:
    name: Teste em DEV    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      # Install required deps for action - jest, jest-html-report
      - name: Install Dependencies
        run: npm install --save-dev jest jest-html-reporter 

      # Finally, run our tests
      - name: Run the tests
        run: npm test
        
      - name: Generate report
        run:  npm test
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: jest-report
          path: './test-report.html'
      - run: echo REALIZANDO TESTES UNITARIOS e SALVANDO O REPORT
      
 
      